# Generated by Django 4.2.7 on 2023-12-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inv',
            field=models.BooleanField(),
        ),
    ]
