# Generated by Django 4.2.7 on 2023-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_book_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inv',
            field=models.BooleanField(default=False),
        ),
    ]
