# Generated by Django 4.2.7 on 2023-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_book_ctgr_category_book_ctgr_b_ctgr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_ctgr',
            old_name='b_title',
            new_name='b_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
