# Generated by Django 4.2.7 on 2023-12-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_b_title_book_ctgr_b_id_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bk_ctg',
        ),
        migrations.DeleteModel(
            name='book_ctgr',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
