# Generated by Django 4.2.7 on 2023-12-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_book_ctgr_category_book_ctgr_b_ctgr_book_ctgr_b_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bk_ctg',
        ),
        migrations.DeleteModel(
            name='book_ctgr',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
