# Generated by Django 4.2.7 on 2023-12-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_category_bk_ctg_delete_book_ctgr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_ctgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=3)),
                ('bk_ctg', models.ManyToManyField(through='app1.book_ctgr', to='app1.book')),
            ],
        ),
        migrations.AddField(
            model_name='book_ctgr',
            name='b_ctgr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.category'),
        ),
        migrations.AddField(
            model_name='book_ctgr',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.book'),
        ),
    ]
